# This workflow will install Python dependencies, run tests and lint with a multiple versions of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update 
            sudo apt install build-essential libopenmpi-dev openmpi-bin libgcc1 libreadline8
        else
            echo "$RUNNER_OS not supported"
            exit 1
        fi
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel pytest-cov coveralls coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Test with pytest
      run: |
        py.test -v hybridLFPy/testing.py
